docker|ci: N_ATTEMPTS, RETRY_DELAY, IFACES params
Expose the following ENV variables as optional params tot the
container:

* `N_ATTEMPTS`: number of attempts on loading the BPF program on an
                interface. Default 6.
* `RETRY_DELAY`: delay between attemps. Default: 3
* `IFACES`: interfaces to load the BPF program. Default: "" (all).

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -113,6 +113,18 @@ jobs:
           grep "Compiling sfunnel with custom ruleset" output || (echo "ERROR: unable to validate it loads custom ruleset via SFUNNEL_RULESET" && exit 1)
           grep "$RULE" output || (echo "ERROR: unable to validate it loads custom ruleset via SFUNNEL_RULESET" && exit 1)
 
+      - name: "[TEST] Run container with custom params ..."
+        run: |
+          set -o pipefail
+          docker run -e N_ATTEMPTS=7 -e RETRY_DELAY=3 -e IFACES="lo" --privileged sfunnel:latest 2>&1 | tee output
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+            echo "ERROR: container execution FAILED!"
+            exit 1
+          fi
+          grep "\$N_ATTEMPTS='7'" output || (echo "ERROR: unable to validate it loads params (N_ATTEMPTS)" && exit 1)
+          grep "\$RETRY_DELAY='3'" output || (echo "ERROR: unable to validate it loads params (RETRY_DELAY)" && exit 1)
+          grep "\$IFACES='lo'" output || (echo "ERROR: unable to validate it loads params (IFACES)" && exit 1)
+
       - name: "Push to ghcr"
         run: |
           if [[ "${EXACT_TAG}" != "" ]]; then
