ci: add CNI test coverage
This commit adds CI coverage for TCP over TCP on the following CNIs:

* cilium
* calico
* flannel
* kindnet (default minikube)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,7 +12,7 @@ permissions:
   packages: write
 
 jobs:
-  make_check:
+  check_unit:
     strategy:
       fail-fast: false
       matrix:
@@ -61,8 +61,48 @@ jobs:
             echo "[${clang}]"
           done
 
+  check_cni_example:
+    strategy:
+      fail-fast: false
+      matrix:
+        combination:
+          - { runner: 'ubuntu-24.04', cni: 'kindnet', debug: '1' }
+          - { runner: 'ubuntu-24.04', cni: 'cilium', debug: '1' }
+          - { runner: 'ubuntu-24.04', cni: 'calico', debug: '1' }
+          - { runner: 'ubuntu-24.04', cni: 'flannel', debug: '1' }
+    runs-on: ${{ matrix.combination.runner }}
+    steps:
+      - name: "Checkout sfunnel"
+        uses: actions/checkout@v4
+        with:
+          path: sfunnel
+          fetch-depth: 0
+          fetch-tags: 1
+
+      - name: "Install deps..."
+        run: |
+          sudo add-apt-repository universe
+          sudo apt-get update
+          sudo apt-get install -y clang make iproute2 \
+                                  bridge-utils python3-scapy python3-pip libbpf-dev \
+                                  libelf-dev linux-headers-generic \
+                                  linux-libc-dev llvm iptables
+          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
+          if [[ "${{ matrix.combination.runner }}" == "ubuntu-24.04" ]]; then
+            sudo apt-get install python3-pytest
+          else
+            sudo pip3 install pytest #pytest binary missing in python3-pytest
+          fi
+
+      - name: "Run CNI test cni='${{ matrix.combination.cni }}'..."
+        run: |
+          cd sfunnel/test/cni/
+          make VERBOSE=1 CNI=${{matrix.combination.cni}} || ( echo "FAILED: test failed with cni='${matrix.combination.cni}' debug='${{matrix.combination.debug}}'" && exit 1 )
+          make VERBOSE=1 _unload #This MUST make the next check fail
+          ( make VERBOSE=1 _check_affinity && ( echo "FAILED: negative test succeeded with cni='${matrix.combination.cni}' debug='${{matrix.combination.debug}}' when it should have failed!" && exit 1 ) ) || true
+
   docker_build_test_publish:
-    needs: [make_check]
+    needs: [check_unit, check_cni_example]
     runs-on: ubuntu-22.04
     steps:
       - name: "Checkout sfunnel"
